### PR TITLE
Do not crash when a single netlink error occurs

### PR DESCRIPTION
**Pull request by lemoer**
Recently, we had the following error:

    Traceback (most recent call last):
      File "/srv/wireguard/vxlan-glue/netlink.py", line 248, in <module>
        manager.push_vxlan_configs()
      File "/srv/wireguard/vxlan-glue/netlink.py", line 139, in push_vxlan_configs
        ip.route(
      File "/usr/lib/python3/dist-packages/pyroute2/iproute/linux.py", line 1909, in route
        ret = self.nlm_request(msg,
      File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 376, in nlm_request
        return tuple(self._genlm_request(*argv, **kwarg))
      File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 867, in nlm_request
        for msg in self.get(msg_seq=msg_seq,
      File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 379, in get
        return tuple(self._genlm_get(*argv, **kwarg))
      File "/usr/lib/python3/dist-packages/pyroute2/netlink/nlsocket.py", line 704, in get
        raise msg['header']['error']
    pyroute2.netlink.exceptions.NetlinkError: (17, 'File exists')

This crashed the program again and again. Hopefully, with this patch it's only skipping the route or fdb addition for one peer and raises an error to the syslog.

So far, the error case is untested.

### CODE REVIEW

**Comment by lemoer** [comment]
The code is currently running on sn10. (Manually pushed via scp)

**Comment by lemoer** [comment]
There are two options how to proceed with this:
1. Just merge it as is (without further testing)
2. Test it. (But how?)

**Comment by 1977er** [comment]
I assume there is no way to reproduce the underlying bug. Since it hapeens rarely, I am ok with 1).

**Comment by lemoer** [comment]
Deployed.

**Pull request merged**
